name: jackett-search-flaresolverr

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    environment:
      LOG_LEVEL: info
    networks:
      - jackett-search
    restart: unless-stopped

networks:
  jackett-search:
    external: true
    name: jackett-search
